### ISSUE TITLE
Nilearn 0.5.0 breaks tests

### ISSUE THREAD

**Issue by oesteban** [nipy/nipype#2791]
### Summary
The latest release of nilearn broke master.

**Comment by djarecka** [comment]
@satra @effigies - do you have any thoughts about `sklearn` version?

I've come back to the `nipype_tutorial` that also didn't like `nilearn` recently, and I moved to 0.4.2, but now heaving issue `ModuleNotFoundError: No module named 'sklearn.externals.joblib'
`, etc. I can explore more and open a new issue with full error, but just wanna check quickly first.

**Comment by satra** [comment]
@djarecka - i thought we just fixed this yesterday on nipype master.

**Comment by effigies** [comment]
You can use sklearn<0.23 or recent nilearn.

**Comment by djarecka** [comment]
@effigies - what do you mean by recent nilearn? When I have `0.6.2` the notebok still fails

**Comment by effigies** [comment]
With `ModuleNotFoundError: No module named 'sklearn.externals.joblib'`? Link to a CI?

**Comment by djarecka** [comment]
@effigies - no, `With ModuleNotFoundError` was with `nilearn` 0.4.2, but after your and Satra's suggestion, I tried once again with master `nipype` and pip-current version of `nilearn` and it seems to me that the problem is exactly the same as 2 months ago (no error, but nipype is hanging when rerunning a workflow). 

Sorry for the confusion, let me run the full example with CI and open an issue.  For now, I was testing locally.

**Comment by djarecka** [comment]
right now, I'm not able to build the image on [circleCI](https://circleci.com/gh/djarecka/nipype_tutorial/534?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), not sure why. Will come back to this tomorrow and let you know
